import { IUser } from "@repo/types/lib/schema/user";
import { IProject, ProjectStatusEnum } from "@repo/types/lib/schema/project";
import { ClientStatusEnum, IClient } from "@repo/types/lib/schema/client";
import { TaskStatusEnum, ITask } from "@repo/types/lib/schema/task";
import { IGroup, GroupTypeEnum } from "@repo/types/lib/schema/group";
import { ITechStack } from "@repo/types/lib/schema/techStack";

export const users: IUser[] = [
  {
    id: 1,
    created_at: new Date("2024-01-10"),
    updated_at: new Date("2024-02-12"),
    email: "",
    created_by: 0,
    updated_by: null,
    full_name: "Alice Johnson",
  },
  {
    id: 2,
    created_at: new Date("2024-03-15"),
    updated_at: new Date("2024-03-22"),
    email: "",
    created_by: 0,
    updated_by: null,
    full_name: "Bob Smith",
  },
  {
    id: 3,
    created_at: new Date("2024-02-20"),
    updated_at: new Date("2024-03-01"),
    email: "",
    created_by: 0,
    updated_by: null,
    full_name: "Charlie Brown",
  },
  {
    id: 4,
    created_at: new Date("2024-04-10"),
    updated_at: new Date("2024-05-05"),
    email: "",
    created_by: 0,
    updated_by: null,
    full_name: "Dana White",
  },
  {
    id: 5,
    created_at: new Date("2024-05-15"),
    updated_at: new Date("2024-06-10"),
    email: "",
    created_by: 0,
    updated_by: null,
    full_name: "Eve Davis",
  },
];

export const projects: IProject[] = [
  {
    id: 101,
    name: "E-commerce Website Development",
    slug: "ecommerce-website-dev",
    description: "Developing a full-stack e-commerce platform.",
    status: ProjectStatusEnum.IN_PROGRESS,
    priority: 1,
    rms_id: "RMS-0001",
    client_id: 1,
    start_date: new Date("2024-04-01"),
    end_date: new Date("2024-10-01"),
    created_at: new Date("2024-01-15"),
    updated_at: new Date("2024-05-12"),
    created_by: 1,
    manager_id: 1,
    updated_by: 2,
  },
  {
    id: 102,
    name: "Mobile App Development",
    slug: "mobile-app-dev",
    description: "Building a mobile app for online banking.",
    status: ProjectStatusEnum.NOT_STARTED,
    priority: 2,
    rms_id: "RMS-0002",
    client_id: 2,
    start_date: new Date("2024-05-01"),
    end_date: new Date("2024-12-01"),
    created_at: new Date("2024-03-01"),
    updated_at: null,
    created_by: 2,
    manager_id: 2,
    updated_by: null,
  },
  {
    id: 103,
    name: "Marketing Campaign",
    slug: "marketing-campaign",
    description: "Designing a digital marketing campaign for product launch.",
    status: ProjectStatusEnum.ON_HOLD,
    priority: 3,
    rms_id: "RMS-0003",
    client_id: 3,
    start_date: new Date("2024-06-01"),
    end_date: new Date("2024-11-01"),
    created_at: new Date("2024-04-01"),
    updated_at: new Date("2024-06-15"),
    created_by: 1,
    manager_id: 1,
    updated_by: 1,
    deleted_at: new Date("2024-09-01"),
    deleted_by: 1,
  },
  {
    id: 104,
    name: "CRM System Upgrade",
    slug: "crm-system-upgrade",
    description: "Upgrading the internal CRM system with new features.",
    status: ProjectStatusEnum.IN_PROGRESS,
    priority: 1,
    rms_id: "RMS-0004",
    client_id: 4,
    start_date: new Date("2024-02-01"),
    end_date: new Date("2024-08-01"),
    created_at: new Date("2024-01-20"),
    updated_at: new Date("2024-04-25"),
    created_by: 3,
    manager_id: 3,
    updated_by: 4,
  },
  {
    id: 105,
    name: "Data Migration Project",
    slug: "data-migration-project",
    description: "Migrating legacy data to a new system.",
    status: ProjectStatusEnum.COMPLETED,
    priority: 2,
    rms_id: "RMS-0005",
    client_id: 4,
    start_date: new Date("2024-01-01"),
    end_date: new Date("2024-06-01"),
    created_at: new Date("2024-02-10"),
    updated_at: new Date("2024-06-05"),
    created_by: 4,
    manager_id: 4,
    updated_by: 2,
  },
  {
    id: 106,
    name: "New Website Launch",
    slug: "new-website-launch",
    description: "Launching a new website for the product portfolio.",
    status: ProjectStatusEnum.ARCHIVED,
    priority: 1,
    rms_id: "RMS-0006",
    client_id: 1,
    start_date: new Date("2024-03-15"),
    end_date: new Date("2024-09-15"),
    created_at: new Date("2024-02-20"),
    updated_at: new Date("2024-10-01"),
    created_by: 5,
    manager_id: 5,
    updated_by: 3,
  },
  {
    id: 107,
    name: "API Integration",
    slug: "api-integration",
    description: "Integrating external APIs into the system.",
    status: ProjectStatusEnum.IN_PROGRESS,
    priority: 3,
    rms_id: "RMS-0007",
    client_id: 1,
    start_date: new Date("2024-05-10"),
    end_date: new Date("2024-12-30"),
    created_at: new Date("2024-03-25"),
    updated_at: new Date("2024-07-20"),
    created_by: 2,
    manager_id: 2,
    updated_by: 5,
  },
  {
    id: 108,
    name: "Cloud Infrastructure Setup",
    slug: "cloud-infrastructure-setup",
    description: "Setting up cloud infrastructure for deployment.",
    status: ProjectStatusEnum.NOT_STARTED,
    priority: 2,
    rms_id: "RMS-0008",
    client_id: 3,
    start_date: new Date("2024-08-01"),
    end_date: new Date("2024-12-01"),
    created_at: new Date("2024-07-01"),
    updated_at: null,
    created_by: 1,
    manager_id: 1,
    updated_by: null,
  },
  {
    id: 109,
    name: "Machine Learning Model Training",
    slug: "ml-model-training",
    description: "Training machine learning models for predictive analysis.",
    status: ProjectStatusEnum.IN_PROGRESS,
    priority: 1,
    rms_id: "RMS-0009",
    client_id: 7,
    start_date: new Date("2024-06-01"),
    end_date: new Date("2024-10-01"),
    created_at: new Date("2024-05-15"),
    updated_at: new Date("2024-07-25"),
    created_by: 3,
    manager_id: 3,
    updated_by: 1,
  },
  {
    id: 110,
    name: "Security Audit",
    slug: "security-audit",
    description: "Performing a comprehensive security audit.",
    status: ProjectStatusEnum.ON_HOLD,
    priority: 3,
    rms_id: "RMS-0010",
    client_id: 10,
    start_date: new Date("2024-09-01"),
    end_date: new Date("2024-11-15"),
    created_at: new Date("2024-08-10"),
    updated_at: new Date("2024-09-25"),
    created_by: 5,
    manager_id: 5,
    updated_by: 2,
  },
];

export const clients: IClient[] = [
  {
    id: 1,
    name: "Tech Innovators",
    slug: "tech-innovators",
    description:
      "A leading tech consulting firm specializing in AI and automation.",
    status: ClientStatusEnum.ACTIVE,
    created_at: new Date("2024-01-01"),
    updated_at: new Date("2024-03-01"),
    created_by: 1,
    updated_by: 2,
  },
  {
    id: 2,
    name: "Green Energy Solutions",
    slug: "green-energy-solutions",
    description:
      "Company focused on renewable energy and sustainability solutions.",
    status: ClientStatusEnum.PENDING,
    created_at: new Date("2024-02-10"),
    updated_at: null,
    created_by: 2,
    updated_by: null,
  },
  {
    id: 3,
    name: "Healthcare Pioneers",
    slug: "healthcare-pioneers",
    description: "Healthcare startup specializing in telemedicine platforms.",
    status: ClientStatusEnum.ACTIVE,
    created_at: new Date("2024-01-15"),
    updated_at: new Date("2024-04-15"),
    created_by: 3,
    updated_by: 4,
  },
  {
    id: 4,
    name: "EduTech Pros",
    slug: "edutech-pros",
    description:
      "Educational technology company providing online learning solutions.",
    status: ClientStatusEnum.SUSPENDED,
    created_at: new Date("2024-03-20"),
    updated_at: new Date("2024-05-20"),
    created_by: 2,
    updated_by: 5,
    deleted_at: new Date("2024-06-15"),
    deleted_by: 1,
  },
  {
    id: 5,
    name: "Retail Revolutionaries",
    slug: "retail-revolutionaries",
    description:
      "Innovative retail company enhancing digital shopping experiences.",
    status: ClientStatusEnum.ACTIVE,
    created_at: new Date("2024-02-28"),
    updated_at: new Date("2024-03-28"),
    created_by: 3,
    updated_by: 2,
  },
  {
    id: 6,
    name: "FinTech Gurus",
    slug: "fintech-gurus",
    description: "Finance technology firm providing digital banking solutions.",
    status: ClientStatusEnum.INACTIVE,
    created_at: new Date("2024-04-01"),
    updated_at: new Date("2024-06-01"),
    created_by: 1,
    updated_by: 3,
  },
  {
    id: 7,
    name: "Global Logistics Corp",
    slug: "global-logistics-corp",
    description:
      "A global company providing supply chain and logistics services.",
    status: ClientStatusEnum.PENDING,
    created_at: new Date("2024-03-15"),
    updated_at: null,
    created_by: 4,
    updated_by: null,
  },
  {
    id: 8,
    name: "Media Masters",
    slug: "media-masters",
    description: "Digital marketing and advertising company.",
    status: ClientStatusEnum.CLOSED,
    created_at: new Date("2024-01-20"),
    updated_at: new Date("2024-02-20"),
    created_by: 2,
    updated_by: 5,
    deleted_at: new Date("2024-04-10"),
    deleted_by: 2,
  },
  {
    id: 9,
    name: "Cloud Wizards",
    slug: "cloud-wizards",
    description: "Cloud services provider offering SaaS and IaaS solutions.",
    status: ClientStatusEnum.ACTIVE,
    created_at: new Date("2024-02-10"),
    updated_at: new Date("2024-04-10"),
    created_by: 5,
    updated_by: 1,
  },
  {
    id: 10,
    name: "Automotive Innovations",
    slug: "automotive-innovations",
    description: "Automobile industry leader in smart vehicle technologies.",
    status: ClientStatusEnum.INACTIVE,
    created_at: new Date("2024-03-05"),
    updated_at: new Date("2024-05-05"),
    created_by: 3,
    updated_by: 4,
  },
];

export const tasks: ITask[] = [
  {
    id: 1,
    name: "Implement authentication system",
    estimated_hours: 40,
    additional_hours: 5,
    start_date: new Date("2024-09-01"),
    end_date: new Date("2024-09-15"),
    assigned_to_id: 2,
    assigned_by_id: 1,
    description: "Implement the login, signup, and token-based authentication",
    status: TaskStatusEnum.IN_PROGRESS,
    priority: 1,
    tech_stack_id: 1,
    group_id: 1,
    project_id: 1,
    created_at: new Date("2024-09-01"),
    updated_at: new Date("2024-09-05"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 2,
    name: "Design database schema",
    estimated_hours: 30,
    start_date: new Date("2024-09-05"),
    end_date: new Date("2024-09-20"),
    assigned_to_id: 3,
    assigned_by_id: 2,
    description: "Create the database schema and relations for the app",
    status: TaskStatusEnum.COMPLETED,
    priority: 2,
    tech_stack_id: 2,
    group_id: 2,
    project_id: 1,
    created_at: new Date("2024-09-05"),
    updated_at: new Date("2024-09-10"),
    created_by: 2,
    updated_by: null,
  },
  {
    id: 3,
    name: "Build REST API for products",
    estimated_hours: 50,
    additional_hours: 10,
    start_date: new Date("2024-09-10"),
    end_date: new Date("2024-09-25"),
    assigned_to_id: 4,
    assigned_by_id: 1,
    description: "Develop the product module for managing items",
    status: TaskStatusEnum.IN_PROGRESS,
    priority: 1,
    tech_stack_id: 1,
    group_id: 1,
    project_id: 2,
    created_at: new Date("2024-09-10"),
    updated_at: new Date("2024-09-12"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 4,
    name: "Setup CI/CD pipeline",
    estimated_hours: 20,
    start_date: new Date("2024-09-15"),
    end_date: new Date("2024-09-30"),
    assigned_to_id: 5,
    assigned_by_id: 2,
    description: "Configure Jenkins for continuous integration and delivery",
    status: TaskStatusEnum.NOT_STARTED,
    priority: 3,
    tech_stack_id: 3,
    group_id: 2,
    project_id: 3,
    created_at: new Date("2024-09-15"),
    updated_at: new Date("2024-09-18"),
    created_by: 2,
    updated_by: null,
  },
  {
    id: 5,
    name: "Implement user permissions",
    estimated_hours: 25,
    additional_hours: 5,
    start_date: new Date("2024-09-18"),
    end_date: new Date("2024-09-25"),
    assigned_to_id: 4,
    assigned_by_id: 1,
    description: "Create roles and permissions for different user types",
    status: TaskStatusEnum.IN_PROGRESS,
    priority: 2,
    tech_stack_id: 1,
    group_id: 1,
    project_id: 4,
    created_at: new Date("2024-09-18"),
    updated_at: new Date("2024-09-22"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 6,
    name: "Optimize database queries",
    estimated_hours: 15,
    start_date: new Date("2024-09-20"),
    end_date: new Date("2024-09-30"),
    assigned_to_id: 3,
    assigned_by_id: 2,
    description: "Improve the performance of slow queries",
    status: TaskStatusEnum.ON_HOLD,
    priority: 1,
    tech_stack_id: 2,
    group_id: 3,
    project_id: 5,
    created_at: new Date("2024-09-20"),
    updated_at: new Date("2024-09-25"),
    created_by: 2,
    updated_by: null,
  },
  {
    id: 7,
    name: "Implement project dashboard",
    estimated_hours: 45,
    start_date: new Date("2024-09-22"),
    end_date: new Date("2024-10-05"),
    assigned_to_id: 2,
    assigned_by_id: 1,
    description: "Create a dashboard for monitoring project activities",
    status: TaskStatusEnum.IN_PROGRESS,
    priority: 1,
    tech_stack_id: 1,
    group_id: 1,
    project_id: 6,
    created_at: new Date("2024-09-22"),
    updated_at: new Date("2024-09-28"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 8,
    name: "Write unit tests for API",
    estimated_hours: 35,
    start_date: new Date("2024-09-25"),
    end_date: new Date("2024-10-10"),
    assigned_to_id: 5,
    assigned_by_id: 3,
    description: "Create unit tests for all API endpoints",
    status: TaskStatusEnum.IN_PROGRESS,
    priority: 2,
    tech_stack_id: 1,
    group_id: 2,
    project_id: 7,
    created_at: new Date("2024-09-25"),
    updated_at: new Date("2024-09-30"),
    created_by: 3,
    updated_by: null,
  },
  {
    id: 9,
    name: "Build frontend for admin panel",
    estimated_hours: 60,
    start_date: new Date("2024-09-27"),
    end_date: new Date("2024-10-15"),
    assigned_to_id: 4,
    assigned_by_id: 1,
    description: "Develop the admin panel frontend using React",
    status: TaskStatusEnum.IN_PROGRESS,
    priority: 1,
    tech_stack_id: 4,
    group_id: 3,
    project_id: 8,
    created_at: new Date("2024-09-27"),
    updated_at: new Date("2024-09-30"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 10,
    name: "Conduct security audit",
    estimated_hours: 20,
    start_date: new Date("2024-10-01"),
    end_date: new Date("2024-10-10"),
    assigned_to_id: 3,
    assigned_by_id: 2,
    description: "Perform a security audit of the entire system",
    status: TaskStatusEnum.NOT_STARTED,
    priority: 1,
    tech_stack_id: 5,
    group_id: 3,
    project_id: 9,
    created_at: new Date("2024-10-01"),
    updated_at: new Date("2024-10-04"),
    created_by: 2,
    updated_by: null,
  },
  {
    id: 11,
    name: "Refactor legacy codebase",
    estimated_hours: 50,
    additional_hours: 5,
    start_date: new Date("2024-10-01"),
    end_date: new Date("2024-10-20"),
    assigned_to_id: 4,
    assigned_by_id: 1,
    description:
      "Refactor old code to meet new project requirements and improve maintainability.",
    status: TaskStatusEnum.IN_PROGRESS,
    priority: 2,
    tech_stack_id: 1,
    group_id: 1,
    project_id: 10,
    created_at: new Date("2024-10-01"),
    updated_at: new Date("2024-10-04"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 12,
    name: "Develop mobile app interface",
    estimated_hours: 70,
    start_date: new Date("2024-10-05"),
    end_date: new Date("2024-10-30"),
    assigned_to_id: 3,
    assigned_by_id: 2,
    description: "Design and implement the UI for the mobile app.",
    status: TaskStatusEnum.NOT_STARTED,
    priority: 1,
    tech_stack_id: 2,
    group_id: 2,
    project_id: 7,
    created_at: new Date("2024-10-05"),
    updated_at: new Date("2024-10-06"),
    created_by: 2,
    updated_by: null,
  },
  {
    id: 13,
    name: "Implement payment gateway integration",
    estimated_hours: 40,
    additional_hours: 8,
    start_date: new Date("2024-10-10"),
    end_date: new Date("2024-10-25"),
    assigned_to_id: 5,
    assigned_by_id: 1,
    description: "Integrate the payment gateway into the e-commerce platform.",
    status: TaskStatusEnum.IN_PROGRESS,
    priority: 1,
    tech_stack_id: 3,
    group_id: 2,
    project_id: 6,
    created_at: new Date("2024-10-10"),
    updated_at: new Date("2024-10-12"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 14,
    name: "Optimize server performance",
    estimated_hours: 25,
    start_date: new Date("2024-10-15"),
    end_date: new Date("2024-10-20"),
    assigned_to_id: 4,
    assigned_by_id: 3,
    description: "Analyze and optimize the server performance under load.",
    status: TaskStatusEnum.ON_HOLD,
    priority: 2,
    tech_stack_id: 1,
    group_id: 3,
    project_id: 8,
    created_at: new Date("2024-10-15"),
    updated_at: new Date("2024-10-17"),
    created_by: 3,
    updated_by: null,
  },
  {
    id: 15,
    name: "Write documentation for API",
    estimated_hours: 15,
    start_date: new Date("2024-10-18"),
    end_date: new Date("2024-10-20"),
    assigned_to_id: 2,
    assigned_by_id: 1,
    description:
      "Complete the developer documentation for all REST API endpoints.",
    status: TaskStatusEnum.IN_PROGRESS,
    priority: 3,
    tech_stack_id: 4,
    group_id: 1,
    project_id: 9,
    created_at: new Date("2024-10-18"),
    updated_at: new Date("2024-10-20"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 16,
    name: "Fix security vulnerabilities",
    estimated_hours: 30,
    start_date: new Date("2024-10-20"),
    end_date: new Date("2024-10-30"),
    assigned_to_id: 5,
    assigned_by_id: 3,
    description:
      "Patch security vulnerabilities found during the security audit.",
    status: TaskStatusEnum.NOT_STARTED,
    priority: 1,
    tech_stack_id: 5,
    group_id: 2,
    project_id: 7,
    created_at: new Date("2024-10-20"),
    updated_at: new Date("2024-10-22"),
    created_by: 3,
    updated_by: null,
  },
  {
    id: 17,
    name: "Test mobile app UI",
    estimated_hours: 20,
    start_date: new Date("2024-10-22"),
    end_date: new Date("2024-10-25"),
    assigned_to_id: 2,
    assigned_by_id: 1,
    description:
      "Perform end-to-end testing of the mobile app's user interface.",
    status: TaskStatusEnum.NOT_STARTED,
    priority: 2,
    tech_stack_id: 2,
    group_id: 1,
    project_id: 6,
    created_at: new Date("2024-10-22"),
    updated_at: new Date("2024-10-23"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 18,
    name: "Set up production environment",
    estimated_hours: 35,
    additional_hours: 5,
    start_date: new Date("2024-10-25"),
    end_date: new Date("2024-11-01"),
    assigned_to_id: 4,
    assigned_by_id: 2,
    description: "Configure the production servers and deploy the application.",
    status: TaskStatusEnum.IN_PROGRESS,
    priority: 1,
    tech_stack_id: 3,
    group_id: 3,
    project_id: 10,
    created_at: new Date("2024-10-25"),
    updated_at: new Date("2024-10-27"),
    created_by: 2,
    updated_by: null,
  },
  {
    id: 19,
    name: "Create CI/CD pipelines for microservices",
    estimated_hours: 60,
    start_date: new Date("2024-11-01"),
    end_date: new Date("2024-11-15"),
    assigned_to_id: 3,
    assigned_by_id: 2,
    description: "Set up and configure CI/CD pipelines for all microservices.",
    status: TaskStatusEnum.NOT_STARTED,
    priority: 1,
    tech_stack_id: 2,
    group_id: 2,
    project_id: 5,
    created_at: new Date("2024-11-01"),
    updated_at: new Date("2024-11-02"),
    created_by: 2,
    updated_by: null,
  },
  {
    id: 20,
    name: "Run load tests on the system",
    estimated_hours: 50,
    start_date: new Date("2024-11-05"),
    end_date: new Date("2024-11-20"),
    assigned_to_id: 4,
    assigned_by_id: 1,
    description:
      "Run comprehensive load tests to check the system's scalability.",
    status: TaskStatusEnum.NOT_STARTED,
    priority: 1,
    tech_stack_id: 3,
    group_id: 3,
    project_id: 8,
    created_at: new Date("2024-11-05"),
    updated_at: new Date("2024-11-06"),
    created_by: 1,
    updated_by: null,
  },
];

export const groups: IGroup[] = [
  {
    id: 1,
    name: "Frontend Development Team",
    type: GroupTypeEnum.FEATURE,
    start_date: new Date("2024-09-01"),
    end_date: new Date("2024-12-01"),
    descriptions: "Responsible for developing the frontend of the application.",
    group_id: null, // No parent group
    project_id: 1, // Linked to project 1
    created_at: new Date("2024-09-01"),
    updated_at: new Date("2024-10-01"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 2,
    name: "Backend Development Team",
    type: GroupTypeEnum.FEATURE,
    start_date: new Date("2024-09-01"),
    end_date: new Date("2024-12-01"),
    descriptions: "Responsible for developing the backend services and APIs.",
    group_id: null, // No parent group
    project_id: 1, // Linked to project 1
    created_at: new Date("2024-09-01"),
    updated_at: new Date("2024-10-01"),
    created_by: 2,
    updated_by: null,
  },
  {
    id: 3,
    name: "QA and Testing Team",
    type: GroupTypeEnum.SPRINT,
    start_date: new Date("2024-10-01"),
    end_date: new Date("2024-11-01"),
    descriptions: "Handles quality assurance and testing for the application.",
    group_id: null, // No parent group
    project_id: 2, // Linked to project 2
    created_at: new Date("2024-10-01"),
    updated_at: new Date("2024-10-05"),
    created_by: 3,
    updated_by: null,
  },
  {
    id: 4,
    name: "DevOps Team",
    type: GroupTypeEnum.FEATURE,
    start_date: new Date("2024-09-15"),
    end_date: new Date("2024-11-15"),
    descriptions: "Responsible for CI/CD pipeline and infrastructure setup.",
    group_id: null, // No parent group
    project_id: 3, // Linked to project 3
    created_at: new Date("2024-09-15"),
    updated_at: new Date("2024-10-01"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 5,
    name: "Mobile Development Team",
    type: GroupTypeEnum.SPRINT,
    start_date: new Date("2024-10-05"),
    end_date: new Date("2024-12-05"),
    descriptions: "Responsible for mobile app development.",
    group_id: null, // No parent group
    project_id: 4, // Linked to project 4
    created_at: new Date("2024-10-05"),
    updated_at: new Date("2024-10-10"),
    created_by: 2,
    updated_by: null,
  },
  {
    id: 6,
    name: "API Development Team",
    type: GroupTypeEnum.FEATURE,
    start_date: new Date("2024-09-01"),
    end_date: new Date("2024-10-30"),
    descriptions: "Responsible for developing and documenting APIs.",
    group_id: null, // No parent group
    project_id: 5, // Linked to project 5
    created_at: new Date("2024-09-01"),
    updated_at: new Date("2024-09-15"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 7,
    name: "Security and Compliance Team",
    type: GroupTypeEnum.SPRINT,
    start_date: new Date("2024-10-10"),
    end_date: new Date("2024-11-10"),
    descriptions:
      "Ensures the application meets security and compliance standards.",
    group_id: null, // No parent group
    project_id: 6, // Linked to project 6
    created_at: new Date("2024-10-10"),
    updated_at: new Date("2024-10-12"),
    created_by: 3,
    updated_by: null,
  },
  {
    id: 8,
    name: "Database Management Team",
    type: GroupTypeEnum.FEATURE,
    start_date: new Date("2024-09-01"),
    end_date: new Date("2024-12-01"),
    descriptions: "Responsible for managing and optimizing databases.",
    group_id: null, // No parent group
    project_id: 7, // Linked to project 7
    created_at: new Date("2024-09-01"),
    updated_at: new Date("2024-10-01"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 9,
    name: "User Experience Team",
    type: GroupTypeEnum.SPRINT,
    start_date: new Date("2024-10-01"),
    end_date: new Date("2024-11-01"),
    descriptions:
      "Focused on improving the overall user experience of the application.",
    group_id: null, // No parent group
    project_id: 8, // Linked to project 8
    created_at: new Date("2024-10-01"),
    updated_at: new Date("2024-10-05"),
    created_by: 2,
    updated_by: null,
  },
  {
    id: 10,
    name: "Research and Development Team",
    type: GroupTypeEnum.FEATURE,
    start_date: new Date("2024-09-15"),
    end_date: new Date("2024-12-15"),
    descriptions: "Explores new technologies and solutions for the future.",
    group_id: null, // No parent group
    project_id: 9, // Linked to project 9
    created_at: new Date("2024-09-15"),
    updated_at: new Date("2024-10-01"),
    created_by: 3,
    updated_by: null,
  },
];

export const techStacks: ITechStack[] = [
  {
    id: 1,
    name: "React",
    description: "A JavaScript library for building user interfaces.",
    created_at: new Date("2024-01-01"),
    updated_at: new Date("2024-10-01"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 2,
    name: "Node.js",
    description: "JavaScript runtime built on Chrome's V8 JavaScript engine.",
    created_at: new Date("2024-01-02"),
    updated_at: new Date("2024-10-01"),
    created_by: 2,
    updated_by: null,
  },
  {
    id: 3,
    name: "Express",
    description: "Fast, unopinionated, minimalist web framework for Node.js.",
    created_at: new Date("2024-01-03"),
    updated_at: new Date("2024-10-01"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 4,
    name: "MongoDB",
    description:
      "Document-oriented NoSQL database used for high volume data storage.",
    created_at: new Date("2024-01-04"),
    updated_at: new Date("2024-10-01"),
    created_by: 2,
    updated_by: null,
  },
  {
    id: 5,
    name: "PostgreSQL",
    description: "Powerfnull, open-source object-relational database system.",
    created_at: new Date("2024-01-05"),
    updated_at: new Date("2024-10-01"),
    created_by: 3,
    updated_by: null,
  },
  {
    id: 6,
    name: "Django",
    description:
      "High-level Python Web framework that encourages rapid development.",
    created_at: new Date("2024-01-06"),
    updated_at: new Date("2024-10-01"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 7,
    name: "Flask",
    description: "A lightweight WSGI web application framework in Python.",
    created_at: new Date("2024-01-07"),
    updated_at: new Date("2024-10-01"),
    created_by: 2,
    updated_by: null,
  },
  {
    id: 8,
    name: "Ruby on Rails",
    description: "A server-side web application framework written in Ruby.",
    created_at: new Date("2024-01-08"),
    updated_at: new Date("2024-10-01"),
    created_by: 3,
    updated_by: null,
  },
  {
    id: 9,
    name: "Flutter",
    description:
      "UI toolkit for building natively compiled applications for mobile, web, and desktop.",
    created_at: new Date("2024-01-09"),
    updated_at: new Date("2024-10-01"),
    created_by: 1,
    updated_by: null,
  },
  {
    id: 10,
    name: "Kubernetes",
    description:
      "Open-source system for automating deployment, scaling, and management of containerized applications.",
    created_at: new Date("2024-01-10"),
    updated_at: new Date("2024-10-01"),
    created_by: 2,
    updated_by: null,
  },
];
