import { IUser } from "@repo/types/lib/schema/user";
import { IProject, ProjectStatusEnum } from "@repo/types/lib/schema/project";

export const users: IUser[] = [
  {
    id: 1,
    created_at: new Date("2024-01-10"),
    updated_at: new Date("2024-02-12"),
    created_by: "system",
    updated_by: "system",
    full_name: "Alice Johnson",
  },
  {
    id: 2,
    created_at: new Date("2024-03-15"),
    updated_at: new Date("2024-03-22"),
    created_by: "system",
    updated_by: "system",
    full_name: "Bob Smith",
  },
  {
    id: 3,
    created_at: new Date("2024-02-20"),
    updated_at: new Date("2024-03-01"),
    created_by: "system",
    updated_by: "system",
    full_name: "Charlie Brown",
  },
  {
    id: 4,
    created_at: new Date("2024-04-10"),
    updated_at: new Date("2024-05-05"),
    created_by: "system",
    updated_by: "system",
    full_name: "Dana White",
  },
  {
    id: 5,
    created_at: new Date("2024-05-15"),
    updated_at: new Date("2024-06-10"),
    created_by: "system",
    updated_by: "system",
    full_name: "Eve Davis",
  },
];

export const projects: IProject[] = [
  {
    id: 101,
    name: "E-commerce Website Development",
    slug: "ecommerce-website-dev",
    description: "Developing a full-stack e-commerce platform.",
    status: ProjectStatusEnum.IN_PROGRESS,
    priority: 1,
    rms_id: "RMS-0001",
    start_date: new Date("2024-04-01"),
    end_date: new Date("2024-10-01"),
    created_at: new Date("2024-01-15"),
    updated_at: new Date("2024-05-12"),
    created_by: "1",
    manager_id: 1,
    updated_by: "2",
  },
  {
    id: 102,
    name: "Mobile App Development",
    slug: "mobile-app-dev",
    description: "Building a mobile app for online banking.",
    status: ProjectStatusEnum.NOT_STARTED,
    priority: 2,
    rms_id: "RMS-0002",
    start_date: new Date("2024-05-01"),
    end_date: new Date("2024-12-01"),
    created_at: new Date("2024-03-01"),
    updated_at: null,
    created_by: "2",
    manager_id: 2,
    updated_by: null,
  },
  {
    id: 103,
    name: "Marketing Campaign",
    slug: "marketing-campaign",
    description: "Designing a digital marketing campaign for product launch.",
    status: ProjectStatusEnum.ON_HOLD,
    priority: 3,
    rms_id: "RMS-0003",
    start_date: new Date("2024-06-01"),
    end_date: new Date("2024-11-01"),
    created_at: new Date("2024-04-01"),
    updated_at: new Date("2024-06-15"),
    created_by: "1",
    manager_id: 1,
    updated_by: "1",
    deleted_at: new Date("2024-09-01"),
    deleted_by: 1,
  },
  {
    id: 104,
    name: "CRM System Upgrade",
    slug: "crm-system-upgrade",
    description: "Upgrading the internal CRM system with new features.",
    status: ProjectStatusEnum.IN_PROGRESS,
    priority: 1,
    rms_id: "RMS-0004",
    start_date: new Date("2024-02-01"),
    end_date: new Date("2024-08-01"),
    created_at: new Date("2024-01-20"),
    updated_at: new Date("2024-04-25"),
    created_by: "3",
    manager_id: 3,
    updated_by: "4",
  },
  {
    id: 105,
    name: "Data Migration Project",
    slug: "data-migration-project",
    description: "Migrating legacy data to a new system.",
    status: ProjectStatusEnum.COMPLETED,
    priority: 2,
    rms_id: "RMS-0005",
    start_date: new Date("2024-01-01"),
    end_date: new Date("2024-06-01"),
    created_at: new Date("2024-02-10"),
    updated_at: new Date("2024-06-05"),
    created_by: "4",
    manager_id: 4,
    updated_by: "2",
  },
  {
    id: 106,
    name: "New Website Launch",
    slug: "new-website-launch",
    description: "Launching a new website for the product portfolio.",
    status: ProjectStatusEnum.ARCHIVED,
    priority: 1,
    rms_id: "RMS-0006",
    start_date: new Date("2024-03-15"),
    end_date: new Date("2024-09-15"),
    created_at: new Date("2024-02-20"),
    updated_at: new Date("2024-10-01"),
    created_by: "5",
    manager_id: 5,
    updated_by: "3",
  },
  {
    id: 107,
    name: "API Integration",
    slug: "api-integration",
    description: "Integrating external APIs into the system.",
    status: ProjectStatusEnum.IN_PROGRESS,
    priority: 3,
    rms_id: "RMS-0007",
    start_date: new Date("2024-05-10"),
    end_date: new Date("2024-12-30"),
    created_at: new Date("2024-03-25"),
    updated_at: new Date("2024-07-20"),
    created_by: "2",
    manager_id: 2,
    updated_by: "5",
  },
  {
    id: 108,
    name: "Cloud Infrastructure Setup",
    slug: "cloud-infrastructure-setup",
    description: "Setting up cloud infrastructure for deployment.",
    status: ProjectStatusEnum.NOT_STARTED,
    priority: 2,
    rms_id: "RMS-0008",
    start_date: new Date("2024-08-01"),
    end_date: new Date("2024-12-01"),
    created_at: new Date("2024-07-01"),
    updated_at: null,
    created_by: "1",
    manager_id: 1,
    updated_by: null,
  },
  {
    id: 109,
    name: "Machine Learning Model Training",
    slug: "ml-model-training",
    description: "Training machine learning models for predictive analysis.",
    status: ProjectStatusEnum.IN_PROGRESS,
    priority: 1,
    rms_id: "RMS-0009",
    start_date: new Date("2024-06-01"),
    end_date: new Date("2024-10-01"),
    created_at: new Date("2024-05-15"),
    updated_at: new Date("2024-07-25"),
    created_by: "3",
    manager_id: 3,
    updated_by: "1",
  },
  {
    id: 110,
    name: "Security Audit",
    slug: "security-audit",
    description: "Performing a comprehensive security audit.",
    status: ProjectStatusEnum.ON_HOLD,
    priority: 3,
    rms_id: "RMS-0010",
    start_date: new Date("2024-09-01"),
    end_date: new Date("2024-11-15"),
    created_at: new Date("2024-08-10"),
    updated_at: new Date("2024-09-25"),
    created_by: "5",
    manager_id: 5,
    updated_by: "2",
  },
];
